CREATE DATABASE AttendanceDB;

USE AttendanceDB; 

CREATE TABLE Student (
    StudentID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
);

CREATE TABLE Teacher (
    TeacherID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
);

CREATE TABLE Class (
    


);